[workspace]

members = [
    "easyfix",
    "easyfix-dictionary",
    "easyfix-messages",
#"easyfix-session",
]

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
