[package]
name = "easyfix-messages"
version = "0.1.5"
authors = ["Łukasz Dańko <lukasz.danko@gmail.com>"]
license = "MIT"
description = "Easy FIX (Financial Information Exchange) toolset - messages."
repository = "https://github.com/ldanko/easyfix"
readme = "README.md"
edition = "2021"

[dependencies]
anyhow = "1.0"
convert_case = "0.5"
itoa = "1.0"
nom = "7.1"
rust_decimal = "1.22"
ryu = "1.0"
serde = "1.0"
serde_derive = "1.0"
thiserror = "1.0"

[build-dependencies]
easyfix-messages-gen = { version = "0.1.4", path = "easyfix-messages-gen" }
